check50:
  checks:
    two positive numbers:
    - run: ./add_two_numbers
      stdin: 1
      stdin: 4
      stdout: 5
      exit: 0 # expect program to exit with exitcode 0
    one pos one neg:
    - run: ./add_two_numbers
      stdin: 11
      stdin: -4
      stdout: 7
      exit: 0 # expect program to exit with exitcode 0
    two neg:
      stdin: -12
      stdin: -14
      stdout: -26
      exit: 0 # expect program to exit with exitcode 0
